# -*- coding: utf-8 -*-
"""ATM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GBaaI9os9P25ACT5QJPaawZ2wNSm_PBe
"""

class Atm:
    def __init__(self, name, account_number, balance):
        self.name = name
        self.account_number = account_number
        self.balance = balance
    
    def __str__(self):
        return "***Fuji Bank ***"

    def deposit(self):
        amount = int(input("Amount you want to deposit."))
        self.amount = amount
        self.balance = self.balance + self.amount
        print(f"Account balance: {self.balance} baht")

    def withdraw(self):
        amount = int(input("Amount you want to withdraw:"))
        self.amount =amount
        if self.amount > self.balance:
            print("No money enough")
        else:
            self.balance = self.balance-self.amount
            print(f"account balance: {self.balance} baht")

    def check_balance(self):
        print(f"account balance: {self.balance} baht")

    def transfer(self):
        trans_Acc_to = int(input("Transfer to?:"))
        trans_money = float(input("Amount you want to transfer?:"))
        self.trans_money = trans_money
        if self.trans_money > self.balance:
            print("No money enough")
        else:
            self.balance = self.balance - self.trans_money
            print(f"account balance: {self.balance} baht")

My_atm = Atm("Bas","1234567",100)
print(My_atm)

My_atm.deposit()
My_atm.withdraw()
My_atm.check_balance()
My_atm.transfer()