# -*- coding: utf-8 -*-
"""Copy of Project_RSP_Game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10LXPkc-5gEBgVDhNbElotlSYV1YVpk3G
"""

## Create function
def rsp_game():
    import random
    move = ["rock", "paper", "scissors", "quit"]
    computer_score = 0
    player_score = 0
    while True:
        player_select = input("Rock Paper Scissors by enter your choice or Quit the game:").lower()
        computer_select = random.choice(move[0:3])

## Condition
        if player_select == "quit":
            print("See You Again")
            break
        elif player_select == "rock" and computer_select == "scissors":
            print ("Win")
            player_score += 1
        elif player_select == "rock" and computer_select == "paper":
            print ("Lose")
            computer_score += 1
        elif player_select == "paper" and computer_select == "scissors":
            print("Lose")
            computer_score += 1
        elif player_select == "paper" and computer_select == "rock":
            print("Win")
            player_score += 1
        elif player_select == "scissors" and computer_select == "rock":
            computer_score += 1
        elif player_select == "scissors" and computer_select == "paper":
            player_score += 1
        elif player_select == computer_select:
            print ("Tie")
        else:
            print("Invalid")
        print(f"Player = {player_select}/ Computer = {computer_select}")
        print(f"Your Score: {player_score}/ Computer_score: {computer_score}")

rsp_game()